# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ring-Camera-Control' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'onnxruntime-objc'

  # Pods for Ring-Camera-Control
end
